# .github/release.yml

name: release
on:
  push:
    branches:
      - master

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: true

      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Set up Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.24.x

      - name: Install deps and build
        run: |
          yarn
          yarn workspaces run build

      # Driver

      - name: Copy readme
        run: cp README.md packages/driver/README.md

      - id: publish_driver
        name: Publish '@star3lord/edgedb' to NPM
        uses: JS-DevTools/npm-publish@v1
        with:
          package: packages/driver/package.json
          token: ${{ secrets.NPM_TOKEN }}
          dry-run: false

      - name: If publish 'edgedb'
        if: steps.publish_driver.outputs.type != 'none'
        run: |
          echo "Published ${{ steps.publish.outputs.type }} version: ${{ steps.publish.outputs.version }}"

      - name: If 'edgedb' version unchanged
        if: steps.publish_driver.outputs.type == 'none'
        run: |
          echo "Version in package.json has not changed. Skipping."
